### ISSUE TITLE
Add English dialogs to the repo

### ISSUE THREAD

**Issue by np-c0mp1ete** [storm-devs/sd-teho-public#1]
Currently the repo contains game dialogs only in Russian.
English translation should be added as well.

**Comment by RostislavU** [comment]
Good afternoon. Do you need help to translation? I can help you

**Comment by np-c0mp1ete** [comment]
@RostislavU sure! any improvements are welcome! there are already russian and english config files in the resource folder. Feel free to open merge requests for your improvements! Also, poke us in the discord chat, if you want to help with further development of the game.
