### ISSUE TITLE
Game Crash during a naval battle

### ISSUE THREAD

**Issue by np-c0mp1ete** [storm-devs/sd-teho-public#3]
In a naval battle, if you shoot with knippers at enemies or they shoot at us with knippers, then at some random moment a stable crash occurs.
error.log refers to void Ship_SailDamage() in scripts
`RUNTIME ERROR - file: sea_ai \ AIShip.c; line: 2126`
[system.log](https://github.com/storm-devs/sd-teho-public/files/6215823/system.log)
[error.log](https://github.com/storm-devs/sd-teho-public/files/6215824/error.log)

**Comment by mitrokosta** [comment]
Was an engine issue, fixed by
https://github.com/storm-devs/storm-engine/pull/65
https://github.com/storm-devs/storm-engine/pull/70
