### ISSUE TITLE
How to build and run the game?

### ISSUE THREAD

**Issue by xahon** [storm-devs/sd-teho-public#4]
What do `Add new debug configuration for the engine target.`, `Set the root of this repository as the current directory: "currentDir": "<SD-TEHO-ROOT>".` and `Run the game from VS.` mean? Can you, please, elaborate on it

**Comment by np-c0mp1ete** [comment]
@xahon, sure! Take a look at this [documentation page](https://docs.microsoft.com/en-us/cpp/build/configure-cmake-debugging-sessions?view=msvc-160)
Feel free to get back at me if something is still not clear.

**Comment by xahon** [comment]
Oh, it's VS thing. I use clion and don't know how to properly configure VS for the project. Where to `Set the root of this repository as the current directory: "currentDir": "<SD-TEHO-ROOT>"`? VS won't autocomplete `currentDir` in `CMakeSettings.json`, it means that there is no such option in that config. Should I set it somewhere else?

**Comment by q4a** [comment]
I added it to my `launch_schema.json`: https://docs.microsoft.com/en-us/cpp/build/launch-vs-schema-reference-cpp?view=msvc-160
Here is how ti looks like for me:
```
{
  "version": "0.2.1",
  "defaults": {},
  "configurations": [
    {
      "type": "default",
      "project": "CMakeLists.txt",
      "projectTarget": "engine.exe (bin\\engine.exe)",
      "currentDir": "D:\\git\\sd-teho-public",
      "name": "engine.exe (bin\\engine.exe)"
    }
  ]
}
```

**Comment by np-c0mp1ete** [comment]
@xahon Clion for sure has similar functionality. Basically, you want to run the program from a specific directory.

**Comment by POMXARK** [comment]
Как запустить ? 
Вызвано исключение по адресу 0x00007FFF942AD759 в engine.exe: исключение Microsoft C++: std::runtime_error по адресу памяти 0x00000076DD0FD238.
Возникло необработанное исключение по адресу 0x00007FFF942AD759 в engine.exe: исключение Microsoft C++: std::runtime_error по адресу памяти 0x00000076DD0FD238.

{
  "version": "0.2.1",
  "defaults": {},
  "configurations": [
    {
      "type": "default",
      "project": "CMakeLists.txt",
      "projectTarget": "engine.exe (bin\\engine.exe)",
      "currentDir": "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Sea Dogs - To Each His Own",
      "name": "engine.exe (bin\\engine.exe)"
    }
  ]
}

**Comment by POMXARK** [comment]
OMG ver master-rus not working, develop-eng good working
